### ISSUE TITLE
Problem when dragging data to nowcasting model

### ISSUE THREAD

**Issue by xmaek** [nbbrd/jdemetra-nowcasting#1]
Hi Mats,

I've got trouble dragging the data to dfm model. The following message occurs. Any idea how could I solve it? thanks a lot,
marek

java.lang.NoClassDefFoundError: ec/tss/tsproviders/utils/MultiLineNameUtil
	at be.nbb.demetra.dfm.DfmModelSpecView$SeriesNameRenderer.getTableCellRendererComponent(DfmModelSpecView.java:461)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at ec.util.grid.swing.XTable.prepareRenderer(XTable.java:179)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at ec.util.grid.swing.XTable.paintComponent(XTable.java:203)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at org.netbeans.swing.tabcontrol.TabbedContainer.paint(TabbedContainer.java:994)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by maggima** [comment]
Hello, that's because the current version of the nowcasting plugin needs the last version of JDemetra+ (develop branch, not the 2.0.0 release) as mentioned in the readme.

You can get the [jdemetra-core](https://github.com/jdemetra/jdemetra-core) and [jdemetra-app](https://github.com/jdemetra/jdemetra-app) from Github and compile them (in that order) with Netbeans or wait for our 2.1.0 release of JDemetra+ in the near future

**Comment by xmaek** [comment]
Dear Matts,



thank you for the quick response. May I ask if you have the tentative date 
for the 2.1.0 release of JDemetra+?




best,

marek 



---------- Původní zpráva ----------
Od: Mats Maggi <notifications@github.com>
Komu: nbbrd/jdemetra-nowcasting <jdemetra-nowcasting@noreply.github.com>
Datum: 16. 12. 2015 8:52:38
Předmět: Re: [jdemetra-nowcasting] Problem when dragging data to nowcasting 
model (#1)

"

Hello, that's because the current version of the nowcasting plugin needs the
last version of JDemetra+ (develop branch, not the 2.0.0 release) as 
mentioned in the readme.

You can get the jdemetra-core(https://github.com/jdemetra/jdemetra-core) and
jdemetra-app(https://github.com/jdemetra/jdemetra-app) from Github and 
compile them (in that order) with Netbeans or wait for our 2.1.0 release of 
JDemetra+ in the near future

—
Reply to this email directly or view it on GitHub
(https://github.com/nbbrd/jdemetra-nowcasting/issues/1#issuecomment-165025644)
. 





"
=

**Comment by maggima** [comment]
Hello Marek, we will make a release before 25th of December.
Regards,
Mats

**Comment by maggima** [comment]
Hello Marek,

For your information, we have released the stable version of [JDemetra+ 2.1.0](https://github.com/jdemetra/jdemetra-app/releases/tag/v2.1.0) !

The pre-release version 2.1.0 of the Nowcasting plugin is available [here](https://github.com/nbbrd/jdemetra-nowcasting/releases/tag/v2.1.0).

Regards,

Mats
